services:
  localpaper:
    container_name: localpaper
    image: medo64/localpaper:latest
    restart: unless-stopped
    environment:
      - LP_HOST=<externalip>
      - LP_TIMEZONE=America/Los_Angeles
    ports:
      - "8084:8084"
    volumes:
      - type: bind
        source: <directory>
        target: /config
        read_only: true
